### ISSUE TITLE
Comma in project parent directory

### ISSUE THREAD

**Issue by glsolaria** [jonathanlermitage/tikione-jacocoverage#9]
I have Netbeans 7.3 projects that are version controlled by a configuration management tool that likes to put commas in the path above the Netbeans project. I cannot, however, use the "Test with JaCoCoverage" on projects that have a common in the project's parent directory because an exception gets thrown.

I was able to reproduce the problem as follows:
1. I created a simple HelloWorld project in Netbeans.
2. I verified that I could successfully "Test with JaCoCoverage". 
3. I closed the project.
4. I moved the project directory under a parent directory called "HelloWorld,Comma" 
5. I opened the moved project in Netbeans. 
6. I verified that the moved project built and ran fine.
7. But when I selected to "Test with JaCoCoverage", I got the following error: 

Exception in thread "main" java.lang.reflect.InvocationTargetException
FATAL ERROR in native method: processing of -javaagent failed
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:323)
    at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:338)
Caused by: java.lang.IllegalArgumentException: Invalid agent option syntax "includes=helloworld._:helloworld.sayhello._,destfile=/home/glsolaria/NetBeansProjects/HelloWorld,Comma/HelloWorld/jacoco.exec".
    at org.jacoco.agent.rt.internal_9dd1198.core.runtime.AgentOptions.<init>(AgentOptions.java:190)
    at org.jacoco.agent.rt.internal_9dd1198.PreMain.premain(PreMain.java:43)
    ... 6 more
Testsuite: helloworld.sayhello.SayHelloTest
Tests run: 1, Failures: 0, Errors: 1, Time elapsed: 0 sec

I suspect the comma in the absolute path of "destfile" to AgentOptions is causing a problem. Unfortunately I cannot change the closed-source configuration management tool to not use commas in the path. I don't know if this comes from this plugin or from some other library so any guidance you can give me would be greatly appreciated.

**Comment by pierinho13** [comment]
Nice
